name: drawform_flutter_app
description: A cross-platform Flutter application for Drawform.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^7.1.1
  file_picker: ^6.1.1
  # Cross-platform Python integration to call exporter.py from Dart.
  python_ffi: ^0.4.4
  # State management. Feel free to replace with Riverpod or another solution.
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - python/
